name: laporin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.2
  shared_preferences: ^2.2.3
  get_storage: ^2.1.1
  pin_code_fields: ^8.0.1
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.7
  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  gal: ^2.3.2
  image_picker: ^1.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo.png
    - assets/images/visibility.svg

flutter_native_splash:
  color: "#FFFFFF" 
  
  image: assets/images/splashscreen.png
  
  fullscreen: true

  android_12:
    image: assets/images/splashscreen.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
